language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - ruby-head
  - jruby-19mode
  - jruby-head

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

install: ruby -S bundle install --without release development

env:
  global:
    - CI="travis"

script: bundle exec rake spec:ci

notifications:
  email: false
  flowdock: 1da4416b8ff98d1880986472428b1b1b

services:
  - mongodb

branches:
  only:
    - master
    - 1.x-stable

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk8
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk8
    - rvm: 2.1.5
      jdk: openjdk7
    - rvm: 2.1.5
      jdk: oraclejdk8
    - rvm: 2.2.0
      jdk: openjdk7
    - rvm: 2.2.0
      jdk: oraclejdk8
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ruby-head
      jdk: oraclejdk8
